config/routes.rb
Evablanes::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :projects, except: [:show] do
      post :toggle_published, :on => :member
      post :toggle_featured, :on => :member
      post :toggle_in_slider, :on => :member
      post :sort, :on => :collection
      resources :project_pictures, only: [:index, :new, :create]
    end
    resources :project_pictures, only: [:destroy] do
      post :sort, :on => :collection
    end
    resources :photos, only: [:index, :new, :create, :destroy] do
      post :sort, :on => :collection
      post :toggle_published, :on => :member
    end
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end
    resources :key_values, only: [:update]
    match 'about' => 'static#about', as: :about
    match 'home' => 'static#home', as: :home

    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    root to: 'projects#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :projects, only: [:index, :show]
      resources :contact, controller: :contact, only: [:index, :create]
      resources :photos, only: [:index]
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]

      match 'about' => 'static#about', as: :about
    end

    post 'newsletter' => 'newsletter#subscribe', as: 'newsletter_subscribe'

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include RankedModel

  ranks :sort_order

  mount_uploader :picture, PhotoUploader

  before_validation :set_order, on: :create

  scope :published, where(published: true)
  scope :ordered, rank(:sort_order)

  attr_accessible :picture

  private

  def set_order
    self.update_attribute :sort_order_position, :last
  end
end

app/controllers/admin/photos_controller.rb
# encoding: utf-8

class Admin::PhotosController < Admin::ApplicationController
  before_filter :find_photo, only: [:destroy, :sort, :toggle_published]

  def index
    @photos = Photo.ordered
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(params[:photo])

    if @photo.save
      flash[:notice] = "Imatge pujada correctament"
      redirect_to admin_photos_path
    else
      flash[:alert] = "Corregeix els errors del formulari"
      render :action => :new
    end
  end

  def destroy
    @photo.destroy
    flash[:notice] = "Imatge eliminada correctament"
    redirect_to :back
  end

  def sort
    @photo.update_attribute :sort_order_position, params[:sort_order_position]

    if params[:redirect]
      redirect_to :back
    else
      render nothing: true
    end
  end

  def toggle_published
    @photo.toggle!(:published)

    redirect_to :back
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.published.ordered
  end
end

app/views/admin/photos/_header.html.slim
#member-header
  = yield :actions

  h1.page-header
    ' Fotografies
    - if defined? subtitle
      small= subtitle

app/views/admin/photos/index.html.slim
- content_for :actions do
  = link_to 'Nova Imatge', new_admin_photo_path, class: "btn btn-success pull-right"

= render 'header'

project-pictures-list
  - if @photos.any?

    table.table.table-striped.sortable(update_url=sort_admin_photos_path)
      thead
        tr
          td
          th Picture
          th

      thbody
        - @photos.each do |photo|
          tr.item(item_id=photo.id)
            td
              - with_publication(photo) do |copy, klass|
                = link_to copy, toggle_published_admin_photo_path(photo.id), :method => :post, class: "btn btn-mini #{klass}"
            td= image_tag photo.picture.mini.url
            td
              = link_to 'Delete', [:admin, photo], :confirm => "N'estàs segur?", :method => :delete, :class => "btn btn-danger btn-mini btn-margin pull-right"
              = link_to ' ↑ ', sort_admin_photos_path(id: photo.id, sort_order_position: :first, redirect: true), :method => :post, :class => "btn btn-mini pull-right"
  - else
    #none.well No hi ha imatges

app/views/admin/photos/new.html.slim
= render 'header'

#project-pictures-form
  = simple_form_for [:admin, @photo], html: { :class => "form-horizontal" }, defaults: { wrapper: :with_controls, label_html: { class: 'form--horizontal__control-label' } } do |f|

    = f.input :picture, :label => "Picture"

    .controls
      = f.submit 'Crear', :class => "btn btn-primary"