config/routes.rb
Evablanes::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :projects, except: [:show] do
      post :toggle_published, :on => :member
      post :toggle_featured, :on => :member
      post :toggle_in_slider, :on => :member
      post :sort, :on => :collection
      resources :project_pictures, only: [:index, :new, :create]
    end
    resources :project_pictures, only: [:destroy] do
      post :sort, :on => :collection
    end
    resources :photos, only: [:index, :new, :create, :destroy] do
      post :sort, :on => :collection
      post :toggle_published, :on => :member
    end
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end
    resources :key_values, only: [:update]
    match 'about' => 'static#about', as: :about
    match 'home' => 'static#home', as: :home

    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    root to: 'projects#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :projects, only: [:index, :show]
      resources :contact, controller: :contact, only: [:index, :create]
      resources :photos, only: [:index]
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]

      match 'about' => 'static#about', as: :about
    end

    post 'newsletter' => 'newsletter#subscribe', as: 'newsletter_subscribe'

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/views/shared/_footer.html.slim
.container
  .footer
    .footer-filet= image_tag asset_path('down_arrow.png')
    .footer-newsletter
      span.red
        =' t('.sign_up_to_my_newsletter')
      = t('.promise')
      .newsletter-form
        = form_tag newsletter_subscribe_path, id: 'newsletter_form' do
          = text_field_tag('email', nil, placeholder: t('.write_your_email'), class: 'newsletter-input span3' )
          a.newsletter-link(href="javascript;")
            span.r-arrow &rarr;
    .footer-social
      ul.social-links
        li.social-link= link_to 'http://www.flickr.com/photos/evablanes', target: '_blank' do
          = image_tag asset_path('social_flickr.png')
        li.social-link= link_to 'http://www.linkedin.com/in/evablanes', target: '_blank' do
          = image_tag asset_path('social_linkedin.png')
        li.social-link= link_to 'http://www.behance.net/evablanes', target: '_blank' do
          = image_tag asset_path('social_behance.png')

app/views/shared/_head.html.slim
head
  title Eva Blanes | Graphic Design & Art Direction
  = stylesheet_link_tag :application
  = csrf_meta_tags
  link(href='https://fonts.googleapis.com/css?family=PT+Serif:400,700|Work+Sans:300,500' rel='stylesheet' type='text/css')
  = favicon_link_tag 'favicon.ico'
  = analytics_init if Rails.env.production?

app/views/shared/_header.html.slim
.container
  header
    .header
      .row
        .span2
          = link_to root_path do
            .header-title Eva Blanes Design
        .span4.header-right
          .header-language-links.dropdown
            a.dropdown-toggle(data-toggle="dropdown")= LANGUAGES_BY_LOCALE[I18n.locale.to_s]
            ul.header-languages.dropdown-menu
              - (LOCALES - [I18n.locale]).each do |locale|
                li.header-language= active_link_to LANGUAGES_BY_LOCALE[locale.to_s], locale_url(:i18n_locale => locale)

          ul.header-nav
            li.header-nav-link= active_link_to t('.contact'), contact_index_path
            /li.header-nav-link= active_link_to t('.publications'), '#'
            li.header-nav-link= active_link_to t('.about_me'), about_path
            li.header-nav-link= active_link_to t('.photography'), photos_path
            li.header-nav-link= active_link_to t('.work'), projects_path