config/routes.rb
Evablanes::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :projects, except: [:show] do
      post :toggle_published, :on => :member
      post :toggle_featured, :on => :member
      post :toggle_in_slider, :on => :member
      post :sort, :on => :collection
      resources :project_pictures, only: [:index, :new, :create]
    end
    resources :project_pictures, only: [:destroy] do
      post :sort, :on => :collection
    end
    resources :photos, only: [:index, :new, :create, :destroy] do
      post :sort, :on => :collection
      post :toggle_published, :on => :member
    end
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end
    resources :key_values, only: [:update]
    match 'about' => 'static#about', as: :about
    match 'home' => 'static#home', as: :home

    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    root to: 'projects#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :projects, only: [:index, :show]
      resources :contact, controller: :contact, only: [:index, :create]
      resources :photos, only: [:index]
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]

      match 'about' => 'static#about', as: :about
    end

    post 'newsletter' => 'newsletter#subscribe', as: 'newsletter_subscribe'

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  include ArmotReloading
  include RankedModel

  ranks :sort_order

  has_many :project_pictures

  armotize :title, :subtitle, :description, :cover_title
  define_localized_accessors_for :title, :subtitle, :description, :cover_title

  mount_uploader :cover_picture, ProjectCoverPictureUploader
  mount_uploader :featured_project_picture, FeaturedProjectPictureUploader
  mount_uploader :slider_picture, SliderPictureUploader

  validates_presence_of :title_en, :title_es, :title_ca, :cover_picture
  validates_uniqueness_of :title, :slug
  validates_presence_of :slider_picture, if: :in_slider

  attr_accessible :title_en, :title_es, :title_ca, :subtitle_en, :subtitle_es, :subtitle_ca,
    :description_en, :description_es, :description_ca,
    :cover_picture, :featured_project_picture, :slider_picture, :sort_order, :cover_cols, :cover_title_en, :cover_title_es, :cover_title_ca,
    :slider_order, :featured_order

  before_validation :set_order, on: :create
  after_save :reload_armot!

  include SlugBuilder
  build_slug column_name: :title

  scope :ordered, rank(:sort_order)
  scope :featured_ordered, order(:featured_order)
  scope :slider_ordered, order(:slider_order)
  scope :published, where(published: true)
  scope :in_slider, where(in_slider: true)
  scope :featured, where(featured: true)
  scope :after, lambda{ |project| where('sort_order > ?', project.sort_order) }

  def to_param
    slug
  end

  def self.find_for_show(slug)
    find_by_slug(slug)
  end

  def next_or_first
    Project.published.ordered.after(self).first || Project.published.ordered.first
  end

  private

  def set_order
    self.update_attribute :sort_order_position, :last
  end
end

app/controllers/admin/projects_controller.rb
# encoding: utf-8

class Admin::ProjectsController < Admin::ApplicationController
  before_filter :find_project, only: [:edit, :update, :destroy, :toggle_published, :sort, :toggle_in_slider, :toggle_featured]

  def index
    @projects = Project.ordered
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      flash[:notice] = "Projecte creat correctament"
      redirect_to admin_projects_path(@section)
    else
      flash[:alert] = "Corregeix els errors"
      render :action => :new
    end
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Projecte actualitzat correctament"
      redirect_to admin_projects_path(@section)
    else
      flash[:alert] = "Corregeix els errors"
      render :action => :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Projecte eliminat correctament"
    redirect_to :back
  end

  def toggle_published
    @project.toggle!(:published)

    redirect_to :back
  end

  def toggle_in_slider
    @project.toggle!(:in_slider)

    redirect_to :back
  end

  def toggle_featured
    @project.toggle!(:featured)

    redirect_to :back
  end

  def sort
    @project.update_attribute :sort_order_position, params[:sort_order_position]

    render nothing: true
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.published.ordered
  end

  def show
    @project = Project.find_for_show(params[:id])
  end
end

app/views/admin/projects/_edit_header.html.slim
= link_to admin_projects_path(@section), class: 'btn' do
  i class="icon-arrow-left"
  |  Enrere

.projects-edit-menu.tabs-edit-menu
  h1.pull-left
    ' Projectes
    small
      ' Editant
      = @project.title
  ul.nav.nav-pills.pull-left
    li class=(controller_name == 'projects' ? 'active' : '' )
      = link_to "Info", edit_admin_project_path(@project.id)
    li class=(controller_name == 'project_pictures' ? 'active' : '' )
      = link_to "Pictures", admin_project_project_pictures_path(@project.id)
  .info.pull-right
    = yield :actions

app/views/admin/projects/_form.html.slim
.projects-form
  - form_url = @project.new_record? ? admin_projects_path(@section) : admin_project_path(@project.id)
  = simple_form_for [:admin, @project], url: form_url, html: { class: "form-horizontal"}, defaults: { wrapper: :with_controls, label_html: { class: 'form--horizontal__control-label' } } do |f|

    ul.nav.nav-tabs.row-fluid
      - LANGUAGES.each_with_index do |language, index|
        li class="#{index == 0 ? 'active' : ''}"
          = link_to language.first, "##{language.last}", :"data-toggle" => "tab"

    .tab-content.row-fluid.trailer
      - LANGUAGES.map(&:last).each_with_index do |language, index|
        .tab-pane.multilanguage-attributes id=language class="#{index == 0 ?  'active' : ''}"
          = f.input "title_#{language}", label: "Títol (#{language})"
          = f.input "cover_title_#{language}", label: "Títol del Rollover (#{language})", as: :redactor
          = f.input "subtitle_#{language}", label: "Subtítol (#{language})", as: :redactor
          = f.input "description_#{language}", label: "Descripció (#{language})", as: :redactor

    .well
      = f.input :cover_picture
      = f.input :cover_cols, collection: 1..6, include_blank: false, label: 'Columnes de la Cover picture'
    = f.input :featured_project_picture
    = f.input :featured_order, label: 'Ordre del featured'
    = f.input :slider_picture
    = f.input :slider_order, label: 'Ordre del slider'

    .controls
      = f.button :submit, @project.new_record? ? "Create" : "Save", class: 'btn-success'

app/views/admin/projects/_header.html.slim
#member-header
  = yield :actions

  h1.page-header
    ' Projectes
    - if defined? subtitle
      small= subtitle

app/views/admin/projects/edit.html.slim
= render 'edit_header'

= render 'form'

app/views/admin/projects/index.html.slim
- content_for :actions do
  = link_to 'New Project', new_admin_project_path(@section), class: "btn btn-success pull-right"

= render 'header'

- if @projects.any?
  table.table.table-striped.sortable(update_url=sort_admin_projects_path)
    thead
      tr
        th
        th Cover
        th Nº Columnes Cover
        th Títol
        th Subtítol
        th
    tbody
      - @projects.each do |project|
        tr.item(item_id=project.id)
          td
            - with_publication(project) do |copy, klass|
              = link_to copy, toggle_published_admin_project_path(project.id), :method => :post, class: "btn btn-mini #{klass}"
            - with_featuring(project) do |copy, klass|
              = link_to copy, toggle_featured_admin_project_path(project.id), :method => :post, class: "btn btn-mini #{klass}"
            - with_slider(project) do |copy, klass|
              = link_to copy, toggle_in_slider_admin_project_path(project.id), :method => :post, class: "btn btn-mini #{klass}"
          td
            - if project.cover_picture.present?
              = image_tag project.cover_picture.mini.url
            - else
              | No picture
          td= project.cover_cols
          td= project.title
          td= project.subtitle.try(:html_safe)
          td
            = link_to t('delete', scope: 'actions'), admin_project_path(project.id), confirm: t('you_sure', scope: 'actions'), :method => :delete, class: "btn btn-danger btn-small pull-right"
            = link_to t('edit', scope: 'actions'), edit_admin_project_path(project.id), class: "btn btn-warning btn-small pull-right"
- else
  .well
    | No hi ha projectes

app/views/admin/projects/new.html.slim
= link_to admin_projects_path(@section), class: 'btn' do
  i class="icon-arrow-left"
  |  Enrere

= render 'header', subtitle: 'Nou projecte'

= render 'form'