config/routes.rb
Evablanes::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :projects, except: [:show] do
      post :toggle_published, :on => :member
      post :toggle_featured, :on => :member
      post :toggle_in_slider, :on => :member
      post :sort, :on => :collection
      resources :project_pictures, only: [:index, :new, :create]
    end
    resources :project_pictures, only: [:destroy] do
      post :sort, :on => :collection
    end
    resources :photos, only: [:index, :new, :create, :destroy] do
      post :sort, :on => :collection
      post :toggle_published, :on => :member
    end
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end
    resources :key_values, only: [:update]
    match 'about' => 'static#about', as: :about
    match 'home' => 'static#home', as: :home

    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    root to: 'projects#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :projects, only: [:index, :show]
      resources :contact, controller: :contact, only: [:index, :create]
      resources :photos, only: [:index]
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]

      match 'about' => 'static#about', as: :about
    end

    post 'newsletter' => 'newsletter#subscribe', as: 'newsletter_subscribe'

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/views/admin/shared/_alert.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "error"}"
      = link_to "×", "#", :class => "close", "data-dismiss" => "alert"
      div id="flash_#{name}" = msg

app/views/admin/shared/_menu.html.slim
#admin_menu.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Base", admin_root_path, :class => 'brand'
      - if current_user
        ul.nav
          li= activable_link_to "Projectes", admin_projects_path
          li= activable_link_to "Fotografies", admin_photos_path
          li= activable_link_to "Home", admin_home_path
          li= activable_link_to "About me", admin_about_path
          li= activable_link_to "Usuaris", admin_users_path
          li= activable_link_to "Traduccions", admin_translations_path
      ul.nav.pull-right
        - if logged_in?
          li.name= current_user.email
          li= link_to t('logout', scope: 'actions'), logout_path(:i18n_locale => I18n.locale)

app/views/admin/shared/_submenu.html.slim
.navbar.subnav-fixed
  .navbar-inner
    ul.nav
      = yield :submenu